/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grama.classes.fenetre;

//<editor-fold defaultstate="collapsed" desc=" IMPORTS">
import grama.classes.models.Graphe;
import grama.classes.models.Noeuds;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
//</editor-fold>

/**
 *
 * @author Aro et Idrissa
 */
public class AfficherGraphe extends javax.swing.JFrame {

    //<editor-fold defaultstate="collapsed" desc=" ATTRIBUTS">
    /**
     * correspond à l'objet graphe
     */
    private Graphe graphe;

    /**
     * correspond à l'objet panel
     */
    private PanelAffichage panel;

    /**
     * correspond au premier noeud sélectioné dans {@link #ecran2Pann}
     */
    private static String premierNoeudSelectionéEcran2;

    /**
     * correspond au deuxième noeud sélectioné dans {@link #ecran2Pann}
     */
    private static String deuxiemeNoeudSelectionéEcran2;

    /**
     * correspond au premier noeud sélectioné dans {@link #ecran3Pann}
     */
    private static String premierNoeudSelectionéEcran3;

    /**
     * correspond au deuxième noeud sélectioné dans {@link #ecran3Pann}
     */
    private static String deuxiemeNoeudSelectionéEcran3;

    /**
     * correspond à l'indice sélectionée dans {@link #cb_noeud1Ecran2} ou
     * {@link #cb_noeud1Ecran3}
     */
    private static int item1 = -2;

    /**
     * correspond à l'indice sélectionée dans {@link #cb_noeud2Ecran2} ou
     * {@link #cb_noeud2Ecran3}
     */
    private static int item2 = -2;
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" CONSTRUCTEUR">
    /**
     * Creates new form AfficherGraphe
     *
     * @param graphe
     */
    public AfficherGraphe(Graphe graphe) {
        if (graphe == null) {
            this.graphe = new Graphe();
        } else {
            this.graphe = graphe;
        }
        initComponents();
        initComponentsPerso();
        handleEvnt();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" SETTERS">
    /**
     * modifie la selection par défaut de {@link #rb_tousLesVoisins}
     *
     * @param bool
     */
    public static void setSelectedParDef(boolean bool) {
        rb_tousLesVoisins.setSelected(bool);
    }

    /**
     * modifie le {@link #textArea2}
     *
     * @param string
     */
    public static void setTextArea2(String string) {
        textArea2.setText(string);
    }//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg1dist = new javax.swing.ButtonGroup();
        bgComparaison = new javax.swing.ButtonGroup();
        rightPannel = new javax.swing.JPanel();
        LayoutPannRight = new javax.swing.JPanel();
        ecran0Pann = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbListerParCategorie = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        rb_ville = new javax.swing.JRadioButton();
        rb_restaurant = new javax.swing.JRadioButton();
        rb_loisirs = new javax.swing.JRadioButton();
        rb_autoroutes = new javax.swing.JRadioButton();
        rb_nationales = new javax.swing.JRadioButton();
        rb_departementales = new javax.swing.JRadioButton();
        resultatCompter = new javax.swing.JTextField();
        ecran1Pann = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        rb_tousLesVoisins = new javax.swing.JRadioButton();
        rb_villesDirect = new javax.swing.JRadioButton();
        rb_restaurantDirect = new javax.swing.JRadioButton();
        rb_loisirsDirect = new javax.swing.JRadioButton();
        rb_statistiques = new javax.swing.JRadioButton();
        ecran2Pann = new javax.swing.JPanel();
        textFieldEcran2 = new javax.swing.JTextField();
        btn_valider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_noeud1Ecran2 = new javax.swing.JComboBox<>();
        cb_noeud2Ecran2 = new javax.swing.JComboBox<>();
        ecran3Pann = new javax.swing.JPanel();
        textFieldEcran3 = new javax.swing.JTextField();
        btn_validerEcran3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_noeud1Ecran3 = new javax.swing.JComboBox<>();
        cb_noeud2Ecran3 = new javax.swing.JComboBox<>();
        rb_plusOuverte = new javax.swing.JRadioButton();
        rb_plusGastro = new javax.swing.JRadioButton();
        rb_plusCulturelle = new javax.swing.JRadioButton();
        ecran4Pann = new javax.swing.JPanel();
        textFieldEcran4 = new javax.swing.JTextField();
        btn_validerEcran4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_noeud1Ecran4 = new javax.swing.JComboBox<>();
        cb_noeud2Ecran4 = new javax.swing.JComboBox<>();
        btnEcran0 = new javax.swing.JButton();
        btnEcran1 = new javax.swing.JButton();
        btnEcran2 = new javax.swing.JButton();
        btnEcran3 = new javax.swing.JButton();
        btnEcran4 = new javax.swing.JButton();
        leftPannel = new javax.swing.JPanel();
        btn_redessiner = new javax.swing.JButton();
        panelNoeuds = new javax.swing.JPanel();
        cb_afficheVille = new javax.swing.JCheckBox();
        cb_afficheResto = new javax.swing.JCheckBox();
        btn_quitter = new javax.swing.JCheckBox();
        cb_afficheRien = new javax.swing.JCheckBox();
        panelLoisirs = new javax.swing.JPanel();
        cb_afficheAutoroutes = new javax.swing.JCheckBox();
        cb_afficheNationales = new javax.swing.JCheckBox();
        cb_afficheDepatementales = new javax.swing.JCheckBox();
        cb_afficheRien1 = new javax.swing.JCheckBox();
        tb_afficherBoite = new javax.swing.JToggleButton();
        help = new javax.swing.JLabel();
        etatChargement = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btn_nouveau = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAE GRAMA");
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png"));
        setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());

        rightPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LayoutPannRight.setLayout(new java.awt.CardLayout());

        ecran0Pann.setBorder(javax.swing.BorderFactory.createTitledBorder("Affichage 0 distance"));

        jLabel1.setText("Lister par catégorie");

        cbListerParCategorie.setModel(new ComboModel());
        cbListerParCategorie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbListerParCategorie.setFocusable(false);

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        textArea.setEditable(false);
        textArea.setColumns(5);
        textArea.setRows(5);
        textArea.setTabSize(10);
        textArea.setFocusable(false);
        jScrollPane1.setViewportView(textArea);

        jLabel5.setText("Compter le nombre de");

        buttonGroup1.add(rb_ville);
        rb_ville.setText("Villes");
        rb_ville.setFocusable(false);

        buttonGroup1.add(rb_restaurant);
        rb_restaurant.setText("Restaurant");
        rb_restaurant.setFocusable(false);

        buttonGroup1.add(rb_loisirs);
        rb_loisirs.setText("Centre de loisirs");
        rb_loisirs.setFocusable(false);

        buttonGroup1.add(rb_autoroutes);
        rb_autoroutes.setText("Autoroutes");
        rb_autoroutes.setFocusable(false);

        buttonGroup1.add(rb_nationales);
        rb_nationales.setText("Nationales");
        rb_nationales.setFocusable(false);

        buttonGroup1.add(rb_departementales);
        rb_departementales.setText("Départementales");
        rb_departementales.setFocusable(false);

        resultatCompter.setEditable(false);
        resultatCompter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        resultatCompter.setFocusable(false);

        javax.swing.GroupLayout ecran0PannLayout = new javax.swing.GroupLayout(ecran0Pann);
        ecran0Pann.setLayout(ecran0PannLayout);
        ecran0PannLayout.setHorizontalGroup(
            ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran0PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ecran0PannLayout.createSequentialGroup()
                        .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ecran0PannLayout.createSequentialGroup()
                                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_ville)
                                    .addComponent(rb_loisirs)
                                    .addComponent(rb_nationales))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_departementales, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb_autoroutes)
                                    .addComponent(rb_restaurant)))
                            .addComponent(jLabel5)
                            .addComponent(resultatCompter, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(ecran0PannLayout.createSequentialGroup()
                        .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(ecran0PannLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbListerParCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        ecran0PannLayout.setVerticalGroup(
            ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran0PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbListerParCategorie))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_ville)
                    .addComponent(rb_restaurant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_loisirs)
                    .addComponent(rb_autoroutes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ecran0PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_nationales)
                    .addComponent(rb_departementales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultatCompter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LayoutPannRight.add(ecran0Pann, "ecran0Pann");

        ecran1Pann.setBorder(javax.swing.BorderFactory.createTitledBorder("Voisinage direct 1 distance"));

        jLabel6.setText("Connaitre 1 distance");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        textArea2.setEditable(false);
        textArea2.setColumns(5);
        textArea2.setRows(4);
        textArea2.setText("(veuiiez sélectionner un noeud )");
        textArea2.setFocusable(false);
        jScrollPane2.setViewportView(textArea2);

        bg1dist.add(rb_tousLesVoisins);
        rb_tousLesVoisins.setText("Tous les voisins directs");
        rb_tousLesVoisins.setEnabled(false);
        rb_tousLesVoisins.setFocusable(false);

        bg1dist.add(rb_villesDirect);
        rb_villesDirect.setText("Les villes directes");
        rb_villesDirect.setEnabled(false);
        rb_villesDirect.setFocusable(false);

        bg1dist.add(rb_restaurantDirect);
        rb_restaurantDirect.setText("Les restaurants directs");
        rb_restaurantDirect.setEnabled(false);
        rb_restaurantDirect.setFocusable(false);

        bg1dist.add(rb_loisirsDirect);
        rb_loisirsDirect.setText("Les loisirs directs");
        rb_loisirsDirect.setEnabled(false);
        rb_loisirsDirect.setFocusable(false);

        bg1dist.add(rb_statistiques);
        rb_statistiques.setText("Statistiques");
        rb_statistiques.setEnabled(false);
        rb_statistiques.setFocusable(false);

        javax.swing.GroupLayout ecran1PannLayout = new javax.swing.GroupLayout(ecran1Pann);
        ecran1Pann.setLayout(ecran1PannLayout);
        ecran1PannLayout.setHorizontalGroup(
            ecran1PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran1PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran1PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ecran1PannLayout.createSequentialGroup()
                        .addGroup(ecran1PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(rb_tousLesVoisins)
                            .addComponent(rb_villesDirect)
                            .addComponent(rb_restaurantDirect)
                            .addComponent(rb_loisirsDirect)
                            .addComponent(rb_statistiques))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ecran1PannLayout.setVerticalGroup(
            ecran1PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran1PannLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_tousLesVoisins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_villesDirect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_restaurantDirect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_loisirsDirect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_statistiques)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        LayoutPannRight.add(ecran1Pann, "ecran1Pann");

        ecran2Pann.setBorder(javax.swing.BorderFactory.createTitledBorder("Voisinage à deux sauts 2 distance"));

        textFieldEcran2.setEditable(false);
        textFieldEcran2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldEcran2.setFocusable(false);

        btn_valider.setText("Valider");
        btn_valider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_valider.setFocusable(false);
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        jLabel2.setText("Sélectionner deux noeuds");

        jLabel3.setText("Noeud 1: ");

        jLabel7.setText("Noeud 2:");

        cb_noeud1Ecran2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_noeud1Ecran2.setFocusable(false);

        cb_noeud2Ecran2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_noeud2Ecran2.setFocusable(false);

        javax.swing.GroupLayout ecran2PannLayout = new javax.swing.GroupLayout(ecran2Pann);
        ecran2Pann.setLayout(ecran2PannLayout);
        ecran2PannLayout.setHorizontalGroup(
            ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran2PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEcran2)
                    .addGroup(ecran2PannLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_noeud1Ecran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ecran2PannLayout.createSequentialGroup()
                        .addGroup(ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(btn_valider))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(cb_noeud2Ecran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ecran2PannLayout.setVerticalGroup(
            ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran2PannLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_noeud1Ecran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ecran2PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_noeud2Ecran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addComponent(btn_valider)
                .addGap(14, 14, 14)
                .addComponent(textFieldEcran2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        LayoutPannRight.add(ecran2Pann, "ecran2Pann");

        ecran3Pann.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparaison de 2 sites à 2 sauts ou plus"));

        textFieldEcran3.setEditable(false);
        textFieldEcran3.setText("choisir deux noeuds et valider");
        textFieldEcran3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldEcran3.setEnabled(false);
        textFieldEcran3.setFocusable(false);

        btn_validerEcran3.setText("Valider");
        btn_validerEcran3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_validerEcran3.setFocusable(false);
        btn_validerEcran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerEcran3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Sélectionner deux noeuds");

        jLabel8.setText("Noeud 1: ");

        jLabel9.setText("Noeud 2:");

        cb_noeud1Ecran3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_noeud1Ecran3.setFocusable(false);

        cb_noeud2Ecran3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_noeud2Ecran3.setFocusable(false);

        bgComparaison.add(rb_plusOuverte);
        rb_plusOuverte.setText("Plus ouverte");
        rb_plusOuverte.setEnabled(false);
        rb_plusOuverte.setFocusable(false);

        bgComparaison.add(rb_plusGastro);
        rb_plusGastro.setText("Plus gastronomique");
        rb_plusGastro.setEnabled(false);
        rb_plusGastro.setFocusable(false);

        bgComparaison.add(rb_plusCulturelle);
        rb_plusCulturelle.setText("Plus culturelle");
        rb_plusCulturelle.setEnabled(false);
        rb_plusCulturelle.setFocusable(false);

        javax.swing.GroupLayout ecran3PannLayout = new javax.swing.GroupLayout(ecran3Pann);
        ecran3Pann.setLayout(ecran3PannLayout);
        ecran3PannLayout.setHorizontalGroup(
            ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran3PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEcran3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(ecran3PannLayout.createSequentialGroup()
                        .addGroup(ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(cb_noeud1Ecran3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ecran3PannLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_noeud2Ecran3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ecran3PannLayout.createSequentialGroup()
                        .addGroup(ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_validerEcran3)
                            .addComponent(rb_plusOuverte)
                            .addComponent(rb_plusGastro)
                            .addComponent(rb_plusCulturelle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ecran3PannLayout.setVerticalGroup(
            ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran3PannLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_noeud1Ecran3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ecran3PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_noeud2Ecran3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btn_validerEcran3)
                .addGap(14, 14, 14)
                .addComponent(rb_plusOuverte)
                .addGap(14, 14, 14)
                .addComponent(rb_plusGastro)
                .addGap(14, 14, 14)
                .addComponent(rb_plusCulturelle)
                .addGap(14, 14, 14)
                .addComponent(textFieldEcran3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        LayoutPannRight.add(ecran3Pann, "ecran3Pann");

        ecran4Pann.setBorder(javax.swing.BorderFactory.createTitledBorder("Connaître les distances entre deux sites"));

        textFieldEcran4.setEditable(false);
        textFieldEcran4.setText("choisir deux noeuds et valider");
        textFieldEcran4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldEcran4.setEnabled(false);
        textFieldEcran4.setFocusable(false);

        btn_validerEcran4.setText("Valider");
        btn_validerEcran4.setFocusable(false);

        jLabel10.setText("Sélectionner deux noeuds");

        jLabel11.setText("Noeud 1: ");

        jLabel12.setText("Noeud 2:");

        cb_noeud1Ecran4.setFocusable(false);

        cb_noeud2Ecran4.setFocusable(false);

        javax.swing.GroupLayout ecran4PannLayout = new javax.swing.GroupLayout(ecran4Pann);
        ecran4Pann.setLayout(ecran4PannLayout);
        ecran4PannLayout.setHorizontalGroup(
            ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran4PannLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEcran4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(ecran4PannLayout.createSequentialGroup()
                        .addGroup(ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(cb_noeud1Ecran4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ecran4PannLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_noeud2Ecran4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ecran4PannLayout.createSequentialGroup()
                        .addComponent(btn_validerEcran4)
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ecran4PannLayout.setVerticalGroup(
            ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecran4PannLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(14, 14, 14)
                .addGroup(ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_noeud1Ecran4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ecran4PannLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_noeud2Ecran4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btn_validerEcran4)
                .addGap(116, 116, 116)
                .addComponent(textFieldEcran4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        LayoutPannRight.add(ecran4Pann, "ecran4Pann");

        btnEcran0.setText("Ecran 0");
        btnEcran0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcran0.setFocusable(false);
        btnEcran0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcran0ActionPerformed(evt);
            }
        });

        btnEcran1.setText("Ecran 1");
        btnEcran1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcran1.setFocusable(false);
        btnEcran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcran1ActionPerformed(evt);
            }
        });

        btnEcran2.setText("Ecran 2");
        btnEcran2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcran2.setFocusable(false);
        btnEcran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcran2ActionPerformed(evt);
            }
        });

        btnEcran3.setText("Ecran 3");
        btnEcran3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcran3.setFocusable(false);
        btnEcran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcran3ActionPerformed(evt);
            }
        });

        btnEcran4.setText("Ecran 4");
        btnEcran4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcran4.setEnabled(false);
        btnEcran4.setFocusable(false);
        btnEcran4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcran4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPannelLayout = new javax.swing.GroupLayout(rightPannel);
        rightPannel.setLayout(rightPannelLayout);
        rightPannelLayout.setHorizontalGroup(
            rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LayoutPannRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rightPannelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPannelLayout.createSequentialGroup()
                                .addComponent(btnEcran4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(rightPannelLayout.createSequentialGroup()
                                .addGroup(rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rightPannelLayout.createSequentialGroup()
                                        .addComponent(btnEcran2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEcran3))
                                    .addGroup(rightPannelLayout.createSequentialGroup()
                                        .addComponent(btnEcran0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEcran1)))
                                .addGap(24, 24, 24)))))
                .addContainerGap())
        );
        rightPannelLayout.setVerticalGroup(
            rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEcran0)
                    .addComponent(btnEcran1))
                .addGap(20, 20, 20)
                .addGroup(rightPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEcran2)
                    .addComponent(btnEcran3))
                .addGap(20, 20, 20)
                .addComponent(btnEcran4)
                .addGap(20, 20, 20)
                .addComponent(LayoutPannRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(rightPannel, java.awt.BorderLayout.LINE_END);

        leftPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_redessiner.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_redessiner.setText("Redessiner le Graphe");
        btn_redessiner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_redessiner.setFocusable(false);
        btn_redessiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redessinerActionPerformed(evt);
            }
        });

        panelNoeuds.setBorder(javax.swing.BorderFactory.createTitledBorder("Noeuds"));

        cb_afficheVille.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheVille.setText("Afficher les villes");
        cb_afficheVille.setFocusable(false);
        cb_afficheVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheVilleActionPerformed(evt);
            }
        });

        cb_afficheResto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheResto.setText("Afficher les restaurants");
        cb_afficheResto.setFocusable(false);
        cb_afficheResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheRestoActionPerformed(evt);
            }
        });

        btn_quitter.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_quitter.setText("Afficher les centres de loisirs");
        btn_quitter.setFocusable(false);
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        cb_afficheRien.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheRien.setSelected(true);
        cb_afficheRien.setText("Afficher les noeuds sans leurs noms");
        cb_afficheRien.setFocusable(false);
        cb_afficheRien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheRienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNoeudsLayout = new javax.swing.GroupLayout(panelNoeuds);
        panelNoeuds.setLayout(panelNoeudsLayout);
        panelNoeudsLayout.setHorizontalGroup(
            panelNoeudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoeudsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNoeudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_afficheVille)
                    .addComponent(cb_afficheResto)
                    .addComponent(btn_quitter)
                    .addComponent(cb_afficheRien))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelNoeudsLayout.setVerticalGroup(
            panelNoeudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoeudsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(cb_afficheVille)
                .addGap(10, 10, 10)
                .addComponent(cb_afficheResto)
                .addGap(10, 10, 10)
                .addComponent(btn_quitter)
                .addGap(10, 10, 10)
                .addComponent(cb_afficheRien)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelLoisirs.setBorder(javax.swing.BorderFactory.createTitledBorder("Liens"));

        cb_afficheAutoroutes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheAutoroutes.setText("Afficher les autoroutes");
        cb_afficheAutoroutes.setFocusable(false);
        cb_afficheAutoroutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheAutoroutesActionPerformed(evt);
            }
        });

        cb_afficheNationales.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheNationales.setText("Afficher les nationales");
        cb_afficheNationales.setFocusable(false);
        cb_afficheNationales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheNationalesActionPerformed(evt);
            }
        });

        cb_afficheDepatementales.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheDepatementales.setText("Afficher les départementales");
        cb_afficheDepatementales.setFocusable(false);
        cb_afficheDepatementales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheDepatementalesActionPerformed(evt);
            }
        });

        cb_afficheRien1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cb_afficheRien1.setSelected(true);
        cb_afficheRien1.setText("Afficher les liens sans leurs noms");
        cb_afficheRien1.setFocusable(false);
        cb_afficheRien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_afficheRien1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoisirsLayout = new javax.swing.GroupLayout(panelLoisirs);
        panelLoisirs.setLayout(panelLoisirsLayout);
        panelLoisirsLayout.setHorizontalGroup(
            panelLoisirsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoisirsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoisirsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_afficheAutoroutes)
                    .addComponent(cb_afficheNationales)
                    .addComponent(cb_afficheDepatementales)
                    .addComponent(cb_afficheRien1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelLoisirsLayout.setVerticalGroup(
            panelLoisirsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoisirsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(cb_afficheAutoroutes)
                .addGap(10, 10, 10)
                .addComponent(cb_afficheNationales)
                .addGap(10, 10, 10)
                .addComponent(cb_afficheDepatementales)
                .addGap(10, 10, 10)
                .addComponent(cb_afficheRien1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tb_afficherBoite.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tb_afficherBoite.setText("Afficher les informations du noeud");
        tb_afficherBoite.setFocusable(false);
        tb_afficherBoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_afficherBoiteActionPerformed(evt);
            }
        });

        help.setText("  ❓");
        help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });

        etatChargement.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout etatChargementLayout = new javax.swing.GroupLayout(etatChargement);
        etatChargement.setLayout(etatChargementLayout);
        etatChargementLayout.setHorizontalGroup(
            etatChargementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        etatChargementLayout.setVerticalGroup(
            etatChargementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setText("Ouverture du fichier");

        javax.swing.GroupLayout leftPannelLayout = new javax.swing.GroupLayout(leftPannel);
        leftPannel.setLayout(leftPannelLayout);
        leftPannelLayout.setHorizontalGroup(
            leftPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPannelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etatChargement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelNoeuds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLoisirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tb_afficherBoite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_redessiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        leftPannelLayout.setVerticalGroup(
            leftPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPannelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_redessiner)
                .addGap(10, 10, 10)
                .addGroup(leftPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_afficherBoite)
                    .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(panelNoeuds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(panelLoisirs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(leftPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etatChargement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        getContentPane().add(leftPannel, java.awt.BorderLayout.LINE_START);

        menuFile.setText("Fichier");

        btn_nouveau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_nouveau.setText("Nouveau");
        btn_nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nouveauActionPerformed(evt);
            }
        });
        menuFile.add(btn_nouveau);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFile.add(jMenuItem1);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" GESTION DU CARDLAYOUT">
    private void btnEcran0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcran0ActionPerformed
        ((CardLayout) LayoutPannRight.getLayout()).show(LayoutPannRight, "ecran0Pann");
        PanelAffichage.setColorierNoeud(false);
        PanelAffichage.setColorierLesDeuxNoeuds(false);
        PanelAffichage.setAfficherBoiteDeDialogue(false);
        tb_afficherBoite.setEnabled(true);
        repaint();
    }//GEN-LAST:event_btnEcran0ActionPerformed

    private void btnEcran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcran1ActionPerformed
        ((CardLayout) LayoutPannRight.getLayout()).show(LayoutPannRight, "ecran1Pann");
        PanelAffichage.setColorierNoeud(true);
        PanelAffichage.setColorierLesDeuxNoeuds(false);
        PanelAffichage.setAfficherBoiteDeDialogue(false);
        tb_afficherBoite.setEnabled(false);
        repaint();
    }//GEN-LAST:event_btnEcran1ActionPerformed

    private void btnEcran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcran2ActionPerformed
        ((CardLayout) LayoutPannRight.getLayout()).show(LayoutPannRight, "ecran2Pann");
        if (item1 != -2) {
            cb_noeud1Ecran2.setSelectedIndex(item1);
        }
        if (item2 != -2) {
            cb_noeud2Ecran2.setSelectedIndex(item2);
        }
        PanelAffichage.setColorierNoeud(false);
        PanelAffichage.setColorierLesDeuxNoeuds(true);
        PanelAffichage.setAfficherBoiteDeDialogue(false);
        tb_afficherBoite.setEnabled(false);
        repaint();
    }//GEN-LAST:event_btnEcran2ActionPerformed

    private void btnEcran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcran3ActionPerformed
        ((CardLayout) LayoutPannRight.getLayout()).show(LayoutPannRight, "ecran3Pann");
        if (item1 != -2) {
            cb_noeud1Ecran3.setSelectedIndex(item1);
        }
        if (item2 != -2) {
            cb_noeud2Ecran3.setSelectedIndex(item2);
        }
        PanelAffichage.setColorierNoeud(false);
        PanelAffichage.setColorierLesDeuxNoeuds(true);
        PanelAffichage.setAfficherBoiteDeDialogue(false);
        tb_afficherBoite.setEnabled(false);
        repaint();
    }//GEN-LAST:event_btnEcran3ActionPerformed

    private void btnEcran4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcran4ActionPerformed
        ((CardLayout) LayoutPannRight.getLayout()).show(LayoutPannRight, "ecran4Pann");
        PanelAffichage.setColorierNoeud(false);
        PanelAffichage.setAfficherBoiteDeDialogue(false);
        tb_afficherBoite.setEnabled(false);
        repaint();
    }//GEN-LAST:event_btnEcran4ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" GESTION DES BOUTONS VALIDER">
    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        Noeuds node1 = null;
        Noeuds node2 = null;

        try {
            node1 = graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud(premierNoeudSelectionéEcran2));
            node2 = graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud(deuxiemeNoeudSelectionéEcran2));
        } catch (Exception e) {
        }

        boolean bool = false;
        try {
            bool = graphe.connaitre2Distance(node1, node2);
        } catch (java.lang.NullPointerException e) {
        }

        if (bool) {
            textFieldEcran2.setText("Ils sont à deux distances");
        } else if (bool == false && (node1 == null || node2 == null)) {
            textFieldEcran2.setText("Veuiller selectionner deux noeuds");
        } else {
            textFieldEcran2.setText("Ils ne sont pas à deux distances");
        }
    }//GEN-LAST:event_btn_validerActionPerformed

    private void btn_validerEcran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerEcran3ActionPerformed
        if (premierNoeudSelectionéEcran3 != null && deuxiemeNoeudSelectionéEcran3 != null) {
            this.textFieldEcran3.setEnabled(true);
            this.textFieldEcran3.setText("");
            this.rb_plusOuverte.setEnabled(true);
            this.rb_plusGastro.setEnabled(true);
            this.rb_plusCulturelle.setEnabled(true);
        }
    }//GEN-LAST:event_btn_validerEcran3ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" GESTION DES CHECKBOX DU MENU DE GAUCHE">
    private void cb_afficheVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheVilleActionPerformed
        if (this.cb_afficheVille.isSelected()) {
            PanelAffichage.setEffacerNomVille(true);
            this.cb_afficheRien.setSelected(false);
            repaint();
        }
        if (!this.cb_afficheVille.isSelected()) {
            PanelAffichage.setEffacerNomVille(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheVilleActionPerformed

    private void cb_afficheRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheRestoActionPerformed
        if (this.cb_afficheResto.isSelected()) {
            PanelAffichage.setEffacerNomRestaurant(true);
            this.cb_afficheRien.setSelected(false);
            repaint();
        }
        if (!this.cb_afficheResto.isSelected()) {
            PanelAffichage.setEffacerNomRestaurant(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheRestoActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        if (this.btn_quitter.isSelected()) {
            PanelAffichage.setEffacerNomLoisir(true);
            this.cb_afficheRien.setSelected(false);
            repaint();
        }
        if (!this.btn_quitter.isSelected()) {
            PanelAffichage.setEffacerNomLoisir(false);
            repaint();
        }
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void cb_afficheRienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheRienActionPerformed
        if (this.cb_afficheRien.isSelected()) {
            this.cb_afficheVille.setSelected(false);
            this.cb_afficheResto.setSelected(false);
            this.btn_quitter.setSelected(false);
            PanelAffichage.setEffacerNomNoeuds(false);
            PanelAffichage.setEffacerNomVille(false);
            PanelAffichage.setEffacerNomRestaurant(false);
            PanelAffichage.setEffacerNomLoisir(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheRienActionPerformed

    private void cb_afficheAutoroutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheAutoroutesActionPerformed
        if (this.cb_afficheAutoroutes.isSelected()) {
            PanelAffichage.setEffacerNomAutoroutes(true);
            this.cb_afficheRien1.setSelected(false);
            repaint();
        }
        if (!this.cb_afficheAutoroutes.isSelected()) {
            PanelAffichage.setEffacerNomAutoroutes(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheAutoroutesActionPerformed

    private void cb_afficheNationalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheNationalesActionPerformed
        if (this.cb_afficheNationales.isSelected()) {
            PanelAffichage.setEffacerNomNationales(true);
            this.cb_afficheRien1.setSelected(false);
            repaint();
        }
        if (!this.cb_afficheNationales.isSelected()) {
            PanelAffichage.setEffacerNomNationales(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheNationalesActionPerformed

    private void cb_afficheDepatementalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheDepatementalesActionPerformed
        if (this.cb_afficheDepatementales.isSelected()) {
            PanelAffichage.setEffacerNomDepartementales(true);
            this.cb_afficheRien1.setSelected(false);
            repaint();
        }
        if (!this.cb_afficheDepatementales.isSelected()) {
            PanelAffichage.setEffacerNomDepartementales(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheDepatementalesActionPerformed

    private void cb_afficheRien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_afficheRien1ActionPerformed
        if (this.cb_afficheRien1.isSelected()) {
            this.cb_afficheAutoroutes.setSelected(false);
            this.cb_afficheNationales.setSelected(false);
            this.cb_afficheDepatementales.setSelected(false);
            PanelAffichage.setEffacerNomLiens(false);
            PanelAffichage.setEffacerNomAutoroutes(false);
            PanelAffichage.setEffacerNomNationales(false);
            PanelAffichage.setEffacerNomDepartementales(false);
            repaint();
        }
    }//GEN-LAST:event_cb_afficheRien1ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" BOUTON REDESSINER ET TOGGLE BUTTON">
    private void btn_redessinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redessinerActionPerformed
        panel.genererPosition();
        panel.repaint();
    }//GEN-LAST:event_btn_redessinerActionPerformed

    private void tb_afficherBoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_afficherBoiteActionPerformed
        if (tb_afficherBoite.isSelected()) {
            PanelAffichage.setAfficherBoiteDeDialogue(true);
            repaint();
        } else if (!tb_afficherBoite.isSelected()) {
            PanelAffichage.setAfficherBoiteDeDialogue(false);
            repaint();
        }
    }//GEN-LAST:event_tb_afficherBoiteActionPerformed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        String message = "Cette fonctionalité est disponible uniquement avec Ecran 0.\n"
                + "Elle permet d'avoir des informations sur un noeud donné. Par exemple\n"
                + "son nom, les autres noeuds auxquels il est relié\n"
                + "les liens avec les autres noeuds\n"
                + "et la distance qui les sépare";
        String[] monBouton = {"Fermer"};
        int conf = JOptionPane.showOptionDialog(this, message, "SAE GRAMA",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, monBouton, monBouton[0]);
    }//GEN-LAST:event_helpMouseClicked

    private void btn_nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nouveauActionPerformed
        resetCombo();
        choisirFichier();
        remplirCombo();
        repaint();
        panel.repaint();
    }//GEN-LAST:event_btn_nouveauActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" METHODES PRIVEES">
    public void choisirFichier() {
        JFileChooser chooser = new JFileChooser();
        String extension = "";
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("CSV File (*.csv)", "csv"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("TXT File (*.txt)", "txt"));
        chooser.setApproveButtonText("Ouvir");
        chooser.setDialogTitle("Ouvrir");
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int resultatFichier = chooser.showOpenDialog(null);
        if (resultatFichier == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            int i = file.getAbsolutePath().lastIndexOf('.');
            if (i > 0) {                
                extension = file.getAbsolutePath().substring(i + 1);
            }
            if (file.exists() && (extension.equals("txt") || extension.equals("csv"))) {
                try {
                    graphe.setListeDeNoeuds(graphe.insertionDonnees(file));
                    panel.genererPosition();
                    etatChargement.setBackground(Color.green);
                } catch (IOException ex) {
                    System.out.println("Erreur dans l'insertion des fichiers (IO Exception)");
                }
            }
        }

    }

    private class ComboModel extends DefaultComboBoxModel {

        public ComboModel() {
            addElement("NOEUDS");
            addElement("LIENS");
        }
    }

    /**
     * active les radio button de {@link #ecran1Pann}
     *
     * @param bool
     */
    public static void activateButtonEcran1(boolean bool) {
        rb_tousLesVoisins.setEnabled(bool);
        rb_villesDirect.setEnabled(bool);
        rb_restaurantDirect.setEnabled(bool);
        rb_loisirsDirect.setEnabled(bool);
        rb_statistiques.setEnabled(bool);
    }

    /**
     * détérmine l'indice sélectioné par les combo box des noeuds
     *
     * @param noeud l'indice du noeud qu'on veut
     * @return l'indice
     */
    public int indiceDe(String noeud) {
        int i;
        for (i = 0; i < graphe.getListeDeNoeuds().size(); i++) {
            if (graphe.getListeDeNoeuds().get(i).getNomNoeud().equals(noeud)) {
                break;
            }
        }
        return i;
    }

    /**
     * on rempli la liste de nos combo box
     */
    public void remplirCombo() {

        for (int i = 0; i < graphe.getListeDeNoeuds().size(); i++) {
            cb_noeud1Ecran2.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
            cb_noeud2Ecran2.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
            cb_noeud1Ecran3.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
            cb_noeud2Ecran3.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
            cb_noeud1Ecran4.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
            cb_noeud2Ecran4.addItem(graphe.getListeDeNoeuds().get(i).getNomNoeud());
        }
    }

    public void resetCombo() {
        cb_noeud1Ecran2.removeAllItems();
        cb_noeud2Ecran2.removeAllItems();
        cb_noeud1Ecran3.removeAllItems();
        cb_noeud2Ecran3.removeAllItems();
        cb_noeud1Ecran4.removeAllItems();
        cb_noeud2Ecran4.removeAllItems();
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" CONSTRUCTOR handleEvent + initComponentsPerso">
    /**
     * méthode pour la gestion des événements
     */
    private void handleEvnt() {
        /**
         * Listener sur la combo box de Lister Par categorie du premier écran
         */
        cbListerParCategorie.setSelectedIndex(-1);
        cbListerParCategorie.addItemListener((ItemEvent e) -> {
            if (e.getItem() == "NOEUDS") {
                textArea.setText(graphe.afficheNoeuds(graphe.getListeDeNoeuds(), "tout"));
            } else if (e.getItem() == "LIENS") {
                textArea.setText(graphe.afficheLiens(graphe.getListeDeNoeuds(), "a")
                        + graphe.afficheLiens(graphe.getListeDeNoeuds(), "d")
                        + graphe.afficheLiens(graphe.getListeDeNoeuds(), "n"));
            }
        });

        //<editor-fold defaultstate="collapsed" desc=" ENREGISTREMENT DES RADIO BUTTON">
        /**
         * enregistrement des écouteurs de nos radio button
         */
        rb_ville.addActionListener(new compterListener());
        rb_restaurant.addActionListener(new compterListener());
        rb_loisirs.addActionListener(new compterListener());
        rb_autoroutes.addActionListener(new compterListener());
        rb_nationales.addActionListener(new compterListener());
        rb_departementales.addActionListener(new compterListener());

        rb_tousLesVoisins.addActionListener(new voisinsListener());
        rb_villesDirect.addActionListener(new voisinsListener());
        rb_restaurantDirect.addActionListener(new voisinsListener());
        rb_loisirsDirect.addActionListener(new voisinsListener());
        rb_statistiques.addActionListener(new voisinsListener());

        rb_plusOuverte.addActionListener(new compareListener());
        rb_plusGastro.addActionListener(new compareListener());
        rb_plusCulturelle.addActionListener(new compareListener());

        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc=" REMPLISSAGE DES COMBO BOX">
        /**
         * on rempli la liste de nos combo box
         */
        remplirCombo();
        /**
         * On annule la sélection par défaut. Donc aucun item n'est sélectionné
         */
        cb_noeud1Ecran2.setSelectedIndex(-1);
        cb_noeud2Ecran2.setSelectedIndex(-1);
        cb_noeud1Ecran3.setSelectedIndex(-1);
        cb_noeud2Ecran3.setSelectedIndex(-1);
        cb_noeud1Ecran4.setSelectedIndex(-1);
        cb_noeud2Ecran4.setSelectedIndex(-1);

        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc=" ECOUTEURS DES COMBOS BOX">
        cb_noeud1Ecran2.addItemListener((ItemEvent evt) -> {
            item1 = indiceDe((String) evt.getItem());
            PanelAffichage.setNoeud1Choisi(graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud((String) evt.getItem())));
            premierNoeudSelectionéEcran2 = (String) evt.getItem();
            repaint();
        });

        cb_noeud2Ecran2.addItemListener((ItemEvent evt) -> {
            item2 = indiceDe((String) evt.getItem());
            PanelAffichage.setNoeud2Choisi(graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud((String) evt.getItem())));
            deuxiemeNoeudSelectionéEcran2 = (String) evt.getItem();
            repaint();
        });

        cb_noeud1Ecran3.addItemListener((ItemEvent evt) -> {
            item1 = indiceDe((String) evt.getItem());
            PanelAffichage.setNoeud1Choisi(graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud((String) evt.getItem())));
            premierNoeudSelectionéEcran3 = (String) evt.getItem();
            repaint();
        });

        cb_noeud2Ecran3.addItemListener((ItemEvent evt) -> {
            item2 = indiceDe((String) evt.getItem());
            PanelAffichage.setNoeud2Choisi(graphe.getListeDeNoeuds().get(graphe.getIndiceNoeud((String) evt.getItem())));
            deuxiemeNoeudSelectionéEcran3 = (String) evt.getItem();
            repaint();
        });
        //</editor-fold>

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                AfficherGraphe frame = (AfficherGraphe) e.getSource();
                frame.getPanel().genererPosition();
                frame.getPanel().repaint();
            }
        });
    }

    /**
     * @return le panel
     */
    public PanelAffichage getPanel() {
        return panel;
    }

    /**
     * initComponents personnalisé
     */
    private void initComponentsPerso() {
        panel = new PanelAffichage(graphe);
        this.getContentPane().add(panel);
        this.revalidate();
    }//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" CLASSES INTERNES LISTENERS">
    //ECRAN 0
    class compterListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (rb_ville.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterNoeudByType(graphe.getListeDeNoeuds(), "v")));
            }
            if (rb_restaurant.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterNoeudByType(graphe.getListeDeNoeuds(), "r")));
            }
            if (rb_loisirs.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterNoeudByType(graphe.getListeDeNoeuds(), "l")));
            }
            if (rb_autoroutes.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterLinkByType(graphe.getListeDeNoeuds(), "a")));
            }
            if (rb_nationales.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterLinkByType(graphe.getListeDeNoeuds(), "n")));
            }
            if (rb_departementales.isSelected()) {
                resultatCompter.setText(String.valueOf(graphe.counterLinkByType(graphe.getListeDeNoeuds(), "d")));
            }
        }

    }//fin class compterListener

    //ECRAN 1
    class voisinsListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (rb_tousLesVoisins.isSelected()) {
                Graphe.afficher1Dist(graphe.connaitre1Distance(PanelAffichage.getNoeudclicked()), "tout");
            }
            if (rb_villesDirect.isSelected()) {
                Graphe.afficher1Dist(graphe.connaitre1Distance(PanelAffichage.getNoeudclicked()), "v");
            }
            if (rb_restaurantDirect.isSelected()) {
                Graphe.afficher1Dist(graphe.connaitre1Distance(PanelAffichage.getNoeudclicked()), "r");
            }
            if (rb_loisirsDirect.isSelected()) {
                Graphe.afficher1Dist(graphe.connaitre1Distance(PanelAffichage.getNoeudclicked()), "l");
            }
            if (rb_statistiques.isSelected()) {
                textArea2.setText(Graphe.getStatistique());
            }
        }

    }//fin class voisinsListener

    //ECRAN 3
    class compareListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (rb_plusOuverte.isSelected()) {
                textFieldEcran3.setText(graphe.plusOuverte(premierNoeudSelectionéEcran3, deuxiemeNoeudSelectionéEcran3));
            }

            if (rb_plusGastro.isSelected()) {
                textFieldEcran3.setText(graphe.plusGastronomique(premierNoeudSelectionéEcran3, deuxiemeNoeudSelectionéEcran3));
            }

            if (rb_plusCulturelle.isSelected()) {
                textFieldEcran3.setText(graphe.plusCulturelle(premierNoeudSelectionéEcran3, deuxiemeNoeudSelectionéEcran3));
            }
        }

    }//fin compareListener

    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Variables declaration - do not modify ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutPannRight;
    private javax.swing.ButtonGroup bg1dist;
    private javax.swing.ButtonGroup bgComparaison;
    private javax.swing.JButton btnEcran0;
    private javax.swing.JButton btnEcran1;
    private javax.swing.JButton btnEcran2;
    private javax.swing.JButton btnEcran3;
    private javax.swing.JButton btnEcran4;
    private javax.swing.JMenuItem btn_nouveau;
    private javax.swing.JCheckBox btn_quitter;
    private javax.swing.JButton btn_redessiner;
    private javax.swing.JButton btn_valider;
    private javax.swing.JButton btn_validerEcran3;
    private javax.swing.JButton btn_validerEcran4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbListerParCategorie;
    private javax.swing.JCheckBox cb_afficheAutoroutes;
    private javax.swing.JCheckBox cb_afficheDepatementales;
    private javax.swing.JCheckBox cb_afficheNationales;
    private javax.swing.JCheckBox cb_afficheResto;
    private javax.swing.JCheckBox cb_afficheRien;
    private javax.swing.JCheckBox cb_afficheRien1;
    private javax.swing.JCheckBox cb_afficheVille;
    private static javax.swing.JComboBox<String> cb_noeud1Ecran2;
    private static javax.swing.JComboBox<String> cb_noeud1Ecran3;
    private static javax.swing.JComboBox<String> cb_noeud1Ecran4;
    private javax.swing.JComboBox<String> cb_noeud2Ecran2;
    private javax.swing.JComboBox<String> cb_noeud2Ecran3;
    private javax.swing.JComboBox<String> cb_noeud2Ecran4;
    private javax.swing.JPanel ecran0Pann;
    private javax.swing.JPanel ecran1Pann;
    private javax.swing.JPanel ecran2Pann;
    private javax.swing.JPanel ecran3Pann;
    private javax.swing.JPanel ecran4Pann;
    private static javax.swing.JPanel etatChargement;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftPannel;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPanel panelLoisirs;
    private javax.swing.JPanel panelNoeuds;
    private javax.swing.JRadioButton rb_autoroutes;
    private javax.swing.JRadioButton rb_departementales;
    private javax.swing.JRadioButton rb_loisirs;
    private static javax.swing.JRadioButton rb_loisirsDirect;
    private javax.swing.JRadioButton rb_nationales;
    private javax.swing.JRadioButton rb_plusCulturelle;
    private javax.swing.JRadioButton rb_plusGastro;
    private javax.swing.JRadioButton rb_plusOuverte;
    private javax.swing.JRadioButton rb_restaurant;
    private static javax.swing.JRadioButton rb_restaurantDirect;
    private static javax.swing.JRadioButton rb_statistiques;
    private static javax.swing.JRadioButton rb_tousLesVoisins;
    private javax.swing.JRadioButton rb_ville;
    private static javax.swing.JRadioButton rb_villesDirect;
    private javax.swing.JTextField resultatCompter;
    private javax.swing.JPanel rightPannel;
    private javax.swing.JToggleButton tb_afficherBoite;
    private javax.swing.JTextArea textArea;
    private static javax.swing.JTextArea textArea2;
    private javax.swing.JTextField textFieldEcran2;
    private javax.swing.JTextField textFieldEcran3;
    private javax.swing.JTextField textFieldEcran4;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

}
